name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: action/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --test
